"""empty message

Revision ID: 4f01ba2420d9
Revises: 66c5201c9865
Create Date: 2021-05-08 20:30:28.192953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f01ba2420d9'
down_revision = '66c5201c9865'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('image_url', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie', 'image_url')
    # ### end Alembic commands ###
